# Generated by Django 4.2.11 on 2024-04-17 12:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Başlık')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Açıklama')),
                ('image', models.ImageField(upload_to='products')),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField()),
                ('is_home', models.BooleanField()),
            ],
        ),
    ]
